[platformio]
default_envs = xiao_nrf52840

[env:xiao_nrf52840]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino
monitor_speed = 115200



build_flags =
  -DUSE_TINYUSB
  -DCFG_TUSB_CONFIG_FILE=\"tusb_config.h\"